### ISSUE TITLE
Unable to login - looping

### ISSUE THREAD

**Issue by mbukosky** [mbukosky/SpotifyUnchained#90]
_I tried to use the site, but I keep receiving a message that the app needs to be authorized. Nothing to do on my end?_

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/SpotifyUnchnd">@SpotifyUnchnd</a> When I tap the logo, I&#39;m taken on a loop to this screen,&quot;In order to save playlists, please authorize this app.&quot; (w or w/o login) <a href="https://t.co/uDY8E7Y3Gt">pic.twitter.com/uDY8E7Y3Gt</a></p>&mdash; (((bj))) (@chipotlepepper) <a href="https://twitter.com/chipotlepepper/status/858526328139554817">April 30, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr"><a href="https://twitter.com/SpotifyUnchnd">@SpotifyUnchnd</a> Before I contacted you, I tried Safari on iPhone, Chrome &amp; IE on Win. pc, and Silk on a Fire tablet - all gave variations of the same error.</p>&mdash; (((bj))) (@chipotlepepper) <a href="https://twitter.com/chipotlepepper/status/859199725030875136">May 2, 2017</a></blockquote>

**Comment by mbukosky** [comment]
```Stack trace
TypeError: Cannot read property 'id' of undefined
at /app/app/controllers/users/users.authentication.server.controller.js:47:27
at Layer.handle (/app/node_modules/express/lib/router/layer.js:82:5)
at Layer.wrappedLayerHandleRequest [as handle_request] (/app/node_modules/newrelic/lib/instrumentation/express.js:373:32)
at next (/app/node_modules/express/lib/router/route.js:100:13)
at Route.dispatch (/app/node_modules/express/lib/router/route.js:81:3)
at Layer.wrappedHandle (/app/node_modules/newrelic/lib/instrumentation/express.js:622:19)
at eval (eval at wrapHandle (/app/node_modules/newrelic/lib/instrumentation/express.js:463:19), <anonymous>:3:28)
at Layer.handle (/app/node_modules/express/lib/router/layer.js:8```

**Comment by nichellewheeler** [comment]
Hi Mike! 
I've been experiencing this issue for a while. I last saved NMF playlists to my account back in September 2019.  I've been trying sporadically since then to see if it has resolved, but it doesn't appear to be. If I open an incognito window, I do see the playlists load in normally for a split second, but then the auth message appears. I grabbed a screen capture, in case it's helpful: https://drive.google.com/file/d/1f8VhpfYmy_y51wb21gW9VAxFIJZU7LEa/view?usp=sharing
Any thoughts or progress on this bug?

**Comment by mbukosky** [comment]
Thanks for reaching out. I am busy with personal stuff for the next week, so I will be unable to look into this in detail. But @ joshg4096 might be able to have a look. He is very talented and is currently has nothing to do :)

**Comment by nichellewheeler** [comment]
Thanks, Mike!  I commented on a whim, so I'm just glad you're willing to check it out.  Whenever you ( or @joshg4096 ) can get to it!  :)

**Comment by mbukosky** [comment]
Thanks @joshg4096 . We will start with updating the libs and see if that resolves the issue. https://github.com/mbukosky/SpotifyUnchained/pull/101

**Comment by mbukosky** [comment]
Also testing here - https://github.com/mbukosky/SpotifyUnchained/pull/102

**Comment by mbukosky** [comment]
@nichellewheeler Do you think you can test the login issue on our dev site @ https://spotifyuncha-angular-up-5e3pq4.herokuapp.com/

I think we are going to merge this code into LIVE in the next few days.

**Comment by mbukosky** [comment]
New site is LIVE and looping issue has been fixed. Thanks for the feedback and support.

**Comment by nichellewheeler** [comment]
Hi guys!  Sorry I wasn't available to test over the weekend, but I just tried it out on live and it's working perfectly.  Thank you so much!  Now I have lots of tunes to catch up on. :)
